server:
  port: 18081
spring:
  datasource:
    hikari:
      maximum-pool-size: 2
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
#    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    #      naming:
    #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect

    properties:
      hibernate:
      show_sql: true
      format_sql: true
      use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace